# 1. Environment

In [1]:
from pathlib import Path
import os
import re
import shutil
import pandas as pd
from pandas.errors import EmptyDataError

In [2]:
os.chdir("C:\\Users\\yatsyk\\Documents\\NextCloud_Synchro\\passim_BoH\\")

In [3]:
project_root =  Path(".")
source_dir = project_root / "04.CoMMa" / "00.data" / "02.csvs_pages"
metadata_path = project_root / "04.CoMMa" / "02.metadata" / "196_arkindex_Comma_URL_filled.csv"
concordance_dir = project_root / "01.data" / "05.metadata_from_bases" / "arkindex_pages_id_page_ordering"

project_root, source_dir, metadata_path, concordance_dir

(WindowsPath('.'),
 WindowsPath('04.CoMMa/00.data/02.csvs_pages'),
 WindowsPath('04.CoMMa/02.metadata/196_arkindex_Comma_URL_filled.csv'),
 WindowsPath('01.data/05.metadata_from_bases/arkindex_pages_id_page_ordering'))

# 2. Data fetching

## 2.1. List the csv to align

In [4]:
source_files = sorted(source_dir.glob("*.csv"))
file_list = pd.DataFrame(
    {
        "csv_filename": [path.name for path in source_files],
        "entity_id": [path.stem for path in source_files],
    }
)
print(f"Found {len(file_list)} files")
file_list

Found 196 files

    csv_filename entity_id
0    Q106117.csv   Q106117
1    Q106514.csv   Q106514
2    Q106532.csv   Q106532
3    Q106533.csv   Q106533
4    Q106537.csv   Q106537
..           ...       ...
191   Q70010.csv    Q70010
192   Q70015.csv    Q70015
193   Q70040.csv    Q70040
194   Q77199.csv    Q77199
195   Q77215.csv    Q77215

[196 rows x 2 columns]

## 2.2. Get correspondance ms `entity_id` -> ms `ID Arkindex`

In [5]:
metadata_df = pd.read_csv(metadata_path, dtype=str).fillna("")
metadata_df["entity_id"] = metadata_df["bbma_data_entity"].str.rsplit("/", n=1).str[-1]
metadata_df = metadata_df.rename(columns={"ID Arkindex": "arkindex_id"})
metadata_df

,Manuscript H-ID,bbma_data_entity,arkindex_id,URL CoMMA,Structural annotation,partially annotated,arkindex_comma_pages_matched,Leroquais_annotation,entity_id
0,1356,https://data.biblissima.fr/entity/Q241713,6150a30a-bff0-4672-96c6-9c19896cdc5e,https://comma.inria.fr/doc/https%253A%252F%252...,False,False,True,False,Q241713
1,1429,https://data.biblissima.fr/entity/Q235097,77fcbfe1-faf8-4316-8f32-0155ed3a60c5,https://comma.inria.fr/doc/https%253A%252F%252...,False,True,True,False,Q235097
2,1430,https://data.biblissima.fr/entity/Q235098,034c35ae-17e3-4e51-9821-8cf1662b1253,https://comma.inria.fr/doc/https%253A%252F%252...,False,True,True,False,Q235098
3,1642,https://data.biblissima.fr/entity/Q235484,73e26638-6275-41b9-9502-39e27f01d93f,https://comma.inria.fr/doc/https%253A%252F%252...,False,False,True,False,Q235484
4,1829,https://data.biblissima.fr/entity/Q203702,b3b9759b-56e1-460d-b766-8cee25d6aaa5,https://comma.inria.fr/doc/https%253A%252F%252...,False,True,True,False,Q203702
...,...,...,...,...,...,...,...,...,...
191,3118,https://data.biblissima.fr/entity/Q209026,5fe2eace-2177-4fa0-8c84-2b94b3d88c00,https://comma.inria.fr/doc/https%253A%252F%252...,False,True,True,False,Q209026
192,3119,https://data.biblissima.fr/entity/Q209044,a9a01b20-b6cc-43e1-b3cd-4b57bb3fc270,https://comma.inria.fr/doc/https%253A%252F%252...,False,True,True,False,Q209044
193,3355,https://data.biblissima.fr/entity/Q209755,c0b8fea9-df2b-4518-a55e-5337fa54ce13,https://comma.inria.fr/doc/https%253A%252F%252...,False,True,True,False,Q209755
194,4496,https://data.biblissima.fr/entity/Q211784,bb70bf8b-f365-47a2-9795-37d7c788518c,https://comma.inria.fr/doc/https%253A%252F%252...,False,True,False,False,Q211784
195,4815,https://data.biblissima.fr/entity/Q214011,24ecc34f-2309-48d4-aa59-5f2fb77a6979,https://comma.inria.fr/doc/https%253A%252F%252...,False,True,True,False,Q214011

In [6]:
matches = file_list.merge(
    metadata_df[["entity_id", "arkindex_id", "bbma_data_entity", "Manuscript H-ID"]],
    on="entity_id",
    how="left",
)

missing_arkindex = matches[matches["arkindex_id"].isna() | (matches["arkindex_id"] == "")]
if not missing_arkindex.empty:
    raise ValueError(
        "Found no ID Arkindex for : "
        + ", ".join(missing_arkindex["csv_filename"].tolist())
    )

matches

,csv_filename,entity_id,arkindex_id,bbma_data_entity,Manuscript H-ID
0,Q106117.csv,Q106117,0068e751-c249-4d8b-82f6-07933fe0cecd,https://data.biblissima.fr/entity/Q106117,2513
1,Q106514.csv,Q106514,70aadb9e-fc7f-4583-afef-de71ecca65c6,https://data.biblissima.fr/entity/Q106514,2653
2,Q106532.csv,Q106532,f9f1fca3-072f-4056-9144-8aae1d4a6504,https://data.biblissima.fr/entity/Q106532,2470
3,Q106533.csv,Q106533,e741feb8-6ac4-48f9-8dca-af231bb7b862,https://data.biblissima.fr/entity/Q106533,2452
4,Q106537.csv,Q106537,cbb23979-72fc-48a3-bf59-0963fc91c1ed,https://data.biblissima.fr/entity/Q106537,2426
...,...,...,...,...,...
191,Q70010.csv,Q70010,009c37f0-618a-4d58-b81a-511a36fa0fac,https://data.biblissima.fr/entity/Q70010,2648
192,Q70015.csv,Q70015,b8c8130e-6426-4500-87b2-0059ea8fc7f2,https://data.biblissima.fr/entity/Q70015,2649
193,Q70040.csv,Q70040,c2ec140e-ec75-4ead-9777-544c502a02f9,https://data.biblissima.fr/entity/Q70040,2674
194,Q77199.csv,Q77199,79770f30-cbc9-4bfa-8a6b-0dec987d1ad8,https://data.biblissima.fr/entity/Q77199,2754
195,Q77215.csv,Q77215,60c22da0-28b5-4176-8734-c966db03cafc,https://data.biblissima.fr/entity/Q77215,2761

## 2.3. For every csv find the matching concordance file for alignment

In [7]:
matches["concordance_path"] = matches["arkindex_id"].map(lambda ark_id: concordance_dir / f"{ark_id}.csv")
matches["concordance_exists"] = matches["concordance_path"].map(Path.exists)

missing_concordances = matches[~matches["concordance_exists"]]
if not missing_concordances.empty:
    raise FileNotFoundError(
        "No concordances found for : "
        + ", ".join(missing_concordances["csv_filename"].tolist())
    )

matches[["csv_filename", "entity_id", "arkindex_id", "concordance_path"]]

,csv_filename,entity_id,arkindex_id,concordance_path
0,Q106117.csv,Q106117,0068e751-c249-4d8b-82f6-07933fe0cecd,01.data\05.metadata_from_bases\arkindex_pages_...
1,Q106514.csv,Q106514,70aadb9e-fc7f-4583-afef-de71ecca65c6,01.data\05.metadata_from_bases\arkindex_pages_...
2,Q106532.csv,Q106532,f9f1fca3-072f-4056-9144-8aae1d4a6504,01.data\05.metadata_from_bases\arkindex_pages_...
3,Q106533.csv,Q106533,e741feb8-6ac4-48f9-8dca-af231bb7b862,01.data\05.metadata_from_bases\arkindex_pages_...
4,Q106537.csv,Q106537,cbb23979-72fc-48a3-bf59-0963fc91c1ed,01.data\05.metadata_from_bases\arkindex_pages_...
...,...,...,...,...
191,Q70010.csv,Q70010,009c37f0-618a-4d58-b81a-511a36fa0fac,01.data\05.metadata_from_bases\arkindex_pages_...
192,Q70015.csv,Q70015,b8c8130e-6426-4500-87b2-0059ea8fc7f2,01.data\05.metadata_from_bases\arkindex_pages_...
193,Q70040.csv,Q70040,c2ec140e-ec75-4ead-9777-544c502a02f9,01.data\05.metadata_from_bases\arkindex_pages_...
194,Q77199.csv,Q77199,79770f30-cbc9-4bfa-8a6b-0dec987d1ad8,01.data\05.metadata_from_bases\arkindex_pages_...
195,Q77215.csv,Q77215,60c22da0-28b5-4176-8734-c966db03cafc,01.data\05.metadata_from_bases\arkindex_pages_...

In [32]:
missing_concordances.to_csv("04.CoMMa\\02.metadata\\concordances_arkindex\\missing_concordances.csv")

In [8]:
empty_concordances = []

for path in matches["concordance_path"].dropna().unique():
    path = Path(path)
    if path.exists() and path.stat().st_size == 0:
        empty_concordances.append(path)

empty_concordances

[]

# 3. Add arkindex_page_id to CoMMa transcriptions

In [9]:
csv_dir = Path("04.CoMMa/00.data/02.csvs_pages")

for _, match in matches.iterrows():
    csv_filename = match["csv_filename"]
    concordance_path = Path(match["concordance_path"])

    csv_path = csv_dir / csv_filename

    if not csv_path.exists():
        print(f"CSV not found: {csv_path}")
        continue

    if not concordance_path.exists():
        print(f"Concordance not found: {concordance_path}")
        continue

    df = pd.read_csv(csv_path)
    concordance = pd.read_csv(concordance_path)

    if "page_ordering" not in df.columns:
        print(f"No page_ordering in CSV: {csv_path}")
        continue

    if "page_ordering" not in concordance.columns:
        print(f"No page_ordering in concordance: {concordance_path}")
        continue

    if "arkindex_page_id" not in concordance.columns:
        print(f"No arkindex_page_id in concordance: {concordance_path}")
        continue

    df = df.drop(columns=["arkindex_page_id"], errors="ignore")

    df = df.merge(
        concordance[["page_ordering", "arkindex_page_id"]],
        on="page_ordering",
        how="left",
        validate="one_to_one",
    )

    df.to_csv(csv_path, index=False)

    print(f"Updated: {csv_path}")

Updated: 04.CoMMa\00.data\02.csvs_pages\Q106117.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106514.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106532.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106533.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106537.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106540.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106541.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106543.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106545.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106616.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q106852.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q107627.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q107628.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q107656.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q107662.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109291.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109292.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109588.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109589.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109592.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109594.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109595.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109597.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109599.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109600.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109622.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109835.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q109836.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q118363.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q203702.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q203810.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q207683.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q208917.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q208936.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209025.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209026.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209027.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209028.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209044.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209189.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209191.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209192.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209193.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209199.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209220.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209230.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209231.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209232.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209463.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209464.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q209755.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q211784.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q214011.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q235097.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q235098.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q235484.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q241713.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q241742.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q241751.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q242395.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q261036.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q261827.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q262274.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q276204.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q34269.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q34298.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q365246.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q365254.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q420155.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q422992.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q422993.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q422994.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q46285.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q47860.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q47874.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q48872.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58724.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58742.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58745.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58746.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58747.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58748.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58749.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58750.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58751.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58752.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58810.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58827.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q58836.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59184.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59185.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59195.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59199.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59202.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59208.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59226.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59229.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59235.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59239.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59247.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59252.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59258.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59264.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59278.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59280.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59285.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59289.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59293.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59297.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59302.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59330.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q59407.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60007.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60020.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60132.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60152.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60164.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60165.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60168.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60184.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60209.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60259.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60266.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60273.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60292.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60300.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60303.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60309.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60320.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60328.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60338.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q60403.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q62445.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q62446.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q62448.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q62450.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q66038.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q67077.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q67084.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q67100.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q67107.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q67248.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q67249.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q67250.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q67251.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q68520.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69451.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69677.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69678.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69688.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69704.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69706.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69713.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69716.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69717.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69718.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69719.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69720.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69721.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69722.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69723.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69724.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69725.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69727.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69730.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69752.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69753.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69755.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69756.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69759.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69761.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69763.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69767.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69768.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69770.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69771.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69774.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69775.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69776.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69777.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69778.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69781.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69788.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69790.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69794.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69800.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69802.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69840.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69915.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69917.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q69956.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q70010.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q70015.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q70040.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q77199.csv
Updated: 04.CoMMa\00.data\02.csvs_pages\Q77215.csv

# 4. Rename files using arkindex_ms_id

In [10]:
source_dir = Path("04.CoMMa/00.data/02.csvs_pages")
target_dir = Path("04.CoMMa/00.data/03.csvs_arkindex")

target_dir.mkdir(parents=True, exist_ok=True)

for _, row in matches.iterrows():
    old_name = row["csv_filename"]
    arkindex_id = row["arkindex_id"]

    source_path = source_dir / old_name
    target_path = target_dir / f"{arkindex_id}.csv"

    if not source_path.exists():
        print(f"Source file not found: {source_path}")
        continue

    shutil.copy2(source_path, target_path)

    print(f"Copied: {source_path.name} -> {target_path.name}")

Copied: Q106117.csv -> 0068e751-c249-4d8b-82f6-07933fe0cecd.csv
Copied: Q106514.csv -> 70aadb9e-fc7f-4583-afef-de71ecca65c6.csv
Copied: Q106532.csv -> f9f1fca3-072f-4056-9144-8aae1d4a6504.csv
Copied: Q106533.csv -> e741feb8-6ac4-48f9-8dca-af231bb7b862.csv
Copied: Q106537.csv -> cbb23979-72fc-48a3-bf59-0963fc91c1ed.csv
Copied: Q106540.csv -> ce56cfe8-390c-4227-95d2-211bb48b4e4b.csv
Copied: Q106541.csv -> 6a06c371-4b5d-4f33-b1d9-398b6c2b90c4.csv
Copied: Q106543.csv -> 739f2469-8006-4ed5-acdb-29e748c6af92.csv
Copied: Q106545.csv -> e9cc30a1-1528-411c-970c-57b0e417d964.csv
Copied: Q106616.csv -> 0253a5a1-0667-4c1c-b499-a59d48abc884.csv
Copied: Q106852.csv -> 26c036eb-c249-4720-9229-aa622ad736c2.csv
Copied: Q107627.csv -> ff5abf5d-527f-4db5-9ae0-51222fe71a78.csv
Copied: Q107628.csv -> f2fe9aa4-3856-4f09-ac5a-51b082a3b8e8.csv
Copied: Q107656.csv -> 17a645dc-d1e0-4bbb-8c48-f48ecf5bf4b9.csv
Copied: Q107662.csv -> edde1308-14da-45db-aa7b-a69826fc9324.csv
Copied: Q109291.csv -> f09f92d0-668e-4b32-b813-fc313be71a3a.csv
Copied: Q109292.csv -> c12d6a75-6223-41ad-8a82-0f634a5f2e13.csv
Copied: Q109588.csv -> d1cda616-216c-4cc2-b796-f3b00deaac67.csv
Copied: Q109589.csv -> 2ad57c55-613a-4b07-9853-b0852bd763b6.csv
Copied: Q109592.csv -> 09878703-855a-425e-a0fd-239b83a81de5.csv
Copied: Q109594.csv -> a7bb2ecc-e89c-4805-8378-8dc8163cb582.csv
Copied: Q109595.csv -> cb8cf8d1-59e8-4bfd-9c34-6f35193a4f63.csv
Copied: Q109597.csv -> c91bd11b-ee02-4a1e-8c1b-b82310666875.csv
Copied: Q109599.csv -> 544dc6c3-d5f6-4bff-a89e-57dfa4e8accb.csv
Copied: Q109600.csv -> 8ec3994a-ab25-497e-bb0e-ede0c47d763a.csv
Copied: Q109622.csv -> 98e034ec-9c99-4d46-b7d4-95677c120369.csv
Copied: Q109835.csv -> b812c2af-f58d-49bc-89bb-982cb72e9ee1.csv
Copied: Q109836.csv -> e43c93f2-5f70-475a-8475-8d8131260b3d.csv
Copied: Q118363.csv -> 5d8fd1ad-2d65-4aa8-8938-f4d757b2c840.csv
Copied: Q203702.csv -> b3b9759b-56e1-460d-b766-8cee25d6aaa5.csv
Copied: Q203810.csv -> 6868c4dc-a18c-45a5-b346-2bc9f6a555c2.csv
Copied: Q207683.csv -> 85f2e2d9-4558-4906-93f4-98b64a558c69.csv
Copied: Q208917.csv -> 9a607547-15d2-4dac-a3e2-326d74b4322f.csv
Copied: Q208936.csv -> e696ac54-e46e-4b0a-88b4-7f8e1f08f7ae.csv
Copied: Q209025.csv -> bec31bce-ab48-4a1a-927a-cc83d7237f95.csv
Copied: Q209026.csv -> 5fe2eace-2177-4fa0-8c84-2b94b3d88c00.csv
Copied: Q209027.csv -> a0c5e61b-6e08-444a-a414-1713529ae298.csv
Copied: Q209028.csv -> 886383bb-9a55-4606-90ce-6cc6e5a8f10a.csv
Copied: Q209044.csv -> a9a01b20-b6cc-43e1-b3cd-4b57bb3fc270.csv
Copied: Q209189.csv -> ed07352f-21e8-4cb1-8e52-e8e2a8958936.csv
Copied: Q209191.csv -> 83e37218-68f1-4ed9-9232-f17d79a0314a.csv
Copied: Q209192.csv -> 4aa5efd8-ecdc-4355-8adb-5a758744713d.csv
Copied: Q209193.csv -> 1bba33f4-4982-431f-946b-62147e413b19.csv
Copied: Q209199.csv -> be131102-9d36-4a85-8eb4-0007f9cffccf.csv
Copied: Q209220.csv -> 774f1529-1628-435d-9a1e-39fefb4ba648.csv
Copied: Q209230.csv -> 61334867-7364-4b1e-bfdf-01d12f8aee0f.csv
Copied: Q209231.csv -> a0892db5-9dd9-466a-8983-2c8d96281cc4.csv
Copied: Q209232.csv -> f3128426-28bb-47de-a66a-3da53c0134e3.csv
Copied: Q209463.csv -> 6131c1b7-c521-47fa-9657-618eb4763f62.csv
Copied: Q209464.csv -> f1a47fca-6aca-4aae-9d75-9b836ee118ea.csv
Copied: Q209755.csv -> c0b8fea9-df2b-4518-a55e-5337fa54ce13.csv
Copied: Q211784.csv -> bb70bf8b-f365-47a2-9795-37d7c788518c.csv
Copied: Q214011.csv -> 24ecc34f-2309-48d4-aa59-5f2fb77a6979.csv
Copied: Q235097.csv -> 77fcbfe1-faf8-4316-8f32-0155ed3a60c5.csv
Copied: Q235098.csv -> 034c35ae-17e3-4e51-9821-8cf1662b1253.csv
Copied: Q235484.csv -> 73e26638-6275-41b9-9502-39e27f01d93f.csv
Copied: Q241713.csv -> 6150a30a-bff0-4672-96c6-9c19896cdc5e.csv
Copied: Q241742.csv -> df56b61d-646e-48b1-b0b8-76a102adc8a5.csv
Copied: Q241751.csv -> 8dd96669-48ec-4556-82f6-1df1e48c46f2.csv
Copied: Q242395.csv -> 238af2e2-16a7-4fa5-93e8-b9c79620272c.csv
Copied: Q261036.csv -> aa28246a-8c88-42df-843a-53340feb702a.csv
Copied: Q261827.csv -> 47ad0f42-5f58-4a6c-ac01-8fbb98e0b8af.csv
Copied: Q262274.csv -> cf3b0414-e535-4f20-8dc8-52316b4f7d4a.csv
Copied: Q276204.csv -> 3f5df301-10e6-4833-8110-76d20188ffd5.csv
Copied: Q34269.csv -> 2de4f389-79a1-4047-bf70-f96adb4262bb.csv
Copied: Q34298.csv -> 330f14b9-f6ee-40ba-a414-6bb9e86f6c7b.csv
Copied: Q365246.csv -> ec077e62-52b4-4c7a-bb78-9328899d8822.csv
Copied: Q365254.csv -> cb0bb7a4-14b6-4a49-af00-e1d8cd9bc3c7.csv
Copied: Q420155.csv -> c8b5b12d-bd57-4a52-a88c-66cc2601f589.csv
Copied: Q422992.csv -> dc364c97-758e-4622-8492-1623b49b69a5.csv
Copied: Q422993.csv -> f3dd160b-064e-4ce4-89c5-d916300e038f.csv
Copied: Q422994.csv -> c3f3f006-642b-419d-8b15-8e6dbab11a72.csv
Copied: Q46285.csv -> 9faef44b-a346-4f81-92ca-aadf5c9d50b1.csv
Copied: Q47860.csv -> 8b860405-c988-4e4c-975a-5246a6c0dae8.csv
Copied: Q47874.csv -> 05906f2e-0c51-472d-a1f6-b8d59502057b.csv
Copied: Q48872.csv -> aa3ec7e1-edcd-47b1-ae86-86ee618b0143.csv
Copied: Q58724.csv -> 98efcd16-6ab5-4532-9b40-9c88010738f3.csv
Copied: Q58742.csv -> b4fcd76d-9907-47ef-8672-acf6f026bb37.csv
Copied: Q58745.csv -> 94f75d6a-76ac-486d-a78b-3d3cdef63ae5.csv
Copied: Q58746.csv -> 094b5d7a-c512-4290-924c-81b48dea2fd9.csv
Copied: Q58747.csv -> 75ad7682-7b48-4226-90dd-751d8a4fd938.csv
Copied: Q58748.csv -> c077779b-b6c0-4986-abd9-901fd52354d0.csv
Copied: Q58749.csv -> f3c0a1d5-598f-45cd-a261-bc663666bb70.csv
Copied: Q58750.csv -> c185edee-94f8-412f-b3e3-2c5bb5fe2593.csv
Copied: Q58751.csv -> b381f783-cf7e-41b9-baa0-762d68688194.csv
Copied: Q58752.csv -> bb9f8afc-77b1-4fde-9a45-8152e4ec090c.csv
Copied: Q58810.csv -> d9dd2c1b-6994-4eaa-ade6-fbc0df311a4e.csv
Copied: Q58827.csv -> 9bcf2874-1130-479f-8b6a-8c5f555e9ca3.csv
Copied: Q58836.csv -> 82c6c1e4-ac24-4b3b-ab78-c795c2f3fd66.csv
Copied: Q59184.csv -> 2c2d0d08-927a-40c8-97db-52223c464e89.csv
Copied: Q59185.csv -> 3a230fb6-4f75-480c-9cd4-c70ac2bfc432.csv
Copied: Q59195.csv -> f281aba0-7d24-4136-902d-b08810afb716.csv
Copied: Q59199.csv -> bab3de6f-980c-4b6c-99ab-b438140e949f.csv
Copied: Q59202.csv -> 33d7fd0c-7603-4f24-bd9b-b01d21b8ed54.csv
Copied: Q59208.csv -> 6d6e6acd-393b-4f66-bdd5-4d9f06ad5c24.csv
Copied: Q59226.csv -> f8ac87c1-b602-4093-8bde-419bf7a38c3d.csv
Copied: Q59229.csv -> 70a2eedd-8653-40ef-8284-ad2612e37635.csv
Copied: Q59235.csv -> 098b9a4a-5037-4b57-a010-738c96be1506.csv
Copied: Q59239.csv -> 7c9ed905-8499-452f-86d5-d354b5f1071c.csv
Copied: Q59247.csv -> cf1ecf87-1825-4923-948d-0adf1cceaac0.csv
Copied: Q59252.csv -> 2e5fd8a1-1f44-456b-b3e3-8fc147ba70dc.csv
Copied: Q59258.csv -> ac898936-263d-46bb-8e0a-a3d720b03f2c.csv
Copied: Q59264.csv -> eacdb93a-1018-4f5a-8d02-3313f6d27a25.csv
Copied: Q59278.csv -> 385d36f7-d042-4c43-a260-a480e059ccdd.csv
Copied: Q59280.csv -> cc24f856-d46e-4c7c-908b-5565821f0198.csv
Copied: Q59285.csv -> 9b368755-771a-4457-9ee8-332e548b3e57.csv
Copied: Q59289.csv -> 837e8a45-af01-487b-98d2-f1705b38d867.csv
Copied: Q59293.csv -> 9fb79d58-9c62-49eb-896f-a61ddcccd9e7.csv
Copied: Q59297.csv -> 3ff1cb7d-43ba-41aa-90a9-1dfae271513a.csv
Copied: Q59302.csv -> 16924cb7-fac5-4683-8f11-89cf7f0e5ffe.csv
Copied: Q59330.csv -> 27a9ff14-517c-45cb-a233-c52d62038399.csv
Copied: Q59407.csv -> 54fc41f3-a39f-4375-b7d0-26abc9c71aed.csv
Copied: Q60007.csv -> 22005662-66f9-4803-aa23-80951b7bfadf.csv
Copied: Q60020.csv -> 6fbc9fe5-976a-4778-aac0-38b82f634fe4.csv
Copied: Q60132.csv -> 8c28a6eb-1978-4368-92bf-74af5fad950f.csv
Copied: Q60152.csv -> e3b1fc5f-8410-4ef8-94d4-9421fbefed22.csv
Copied: Q60164.csv -> 69ff71ed-f7d0-47f2-9fe6-b8d218a965aa.csv
Copied: Q60165.csv -> de49ef85-cbf5-48b1-a70d-a44a77f6f9ca.csv
Copied: Q60168.csv -> d2d18aab-f327-424c-b391-361434dde1d0.csv
Copied: Q60184.csv -> 87b6ac6d-df52-4e78-a8c9-560b615d37f3.csv
Copied: Q60209.csv -> 4d70e010-afa1-40fc-8ab3-9b59e2eb7371.csv
Copied: Q60259.csv -> adbef7db-ff17-4e2e-95b2-4425a5bd5838.csv
Copied: Q60266.csv -> d8d587d4-0394-47a2-b540-c564f8ecbd22.csv
Copied: Q60273.csv -> 9acdbfe6-cd66-4671-b83a-12957f42e122.csv
Copied: Q60292.csv -> 66d5edb4-0f54-477e-bb1a-671196506537.csv
Copied: Q60300.csv -> 0be07365-bef9-4533-81cc-3f6248f58663.csv
Copied: Q60303.csv -> 58422672-e5af-402b-b81b-7d928e230c36.csv
Copied: Q60309.csv -> b7cce76f-9297-4fef-b361-1d88c1a7a255.csv
Copied: Q60320.csv -> 003d5be0-3453-46e9-b904-4f6d4f1ee4b5.csv
Copied: Q60328.csv -> 84310118-de8d-41f9-8209-8c63f4f3a631.csv
Copied: Q60338.csv -> bb6587f3-ad2a-48f3-94ca-758e3650e35b.csv
Copied: Q60403.csv -> 02181622-2bcc-4b35-b124-63c701e25860.csv
Copied: Q62445.csv -> 339d3426-ff0c-470f-8467-4bf9677a10f5.csv
Copied: Q62446.csv -> c2fbe77e-b779-48ac-82ad-46a29b5d6562.csv
Copied: Q62448.csv -> 6ddaaadd-ffcc-4433-b7f3-0b4b802a984b.csv
Copied: Q62450.csv -> 2a6dd8ae-86d9-427a-ba48-60ec2bbdd7e0.csv
Copied: Q66038.csv -> 5767de2b-8dea-47d6-b18e-6744c0e5805a.csv
Copied: Q67077.csv -> 6b67c8df-ef4d-40a5-b1b5-ada35871f281.csv
Copied: Q67084.csv -> bd38bf32-d4dc-4e08-a677-7a955c3fa3eb.csv
Copied: Q67100.csv -> 400f000c-4f8c-405e-8531-11d3af24fad7.csv
Copied: Q67107.csv -> a0a16d18-2ebb-47f0-bd4f-17fc08f0b14f.csv
Copied: Q67248.csv -> 6d0f8a3f-ce06-4d48-ace2-46043ac02b6d.csv
Copied: Q67249.csv -> 4f057d86-0d95-4b6f-ac96-aa7968d8c855.csv
Copied: Q67250.csv -> e91794e0-6320-49d5-bd99-f4b42394eb6b.csv
Copied: Q67251.csv -> 71d753bc-6f88-4d39-b301-71f78ba8d39b.csv
Copied: Q68520.csv -> c855a644-405f-4262-bc24-73565c447135.csv
Copied: Q69451.csv -> 0d54dc8b-b5fd-4ced-9191-b59cc5eb198e.csv
Copied: Q69677.csv -> 5365917a-1655-4902-b6bc-e282c0a5f996.csv
Copied: Q69678.csv -> 789f38b4-784e-4f7c-98f3-7d80b374f247.csv
Copied: Q69688.csv -> f411cb6b-7e69-4e08-bdc8-282b62469daa.csv
Copied: Q69704.csv -> afcc0a79-fe57-41b0-b801-a5340a282ddb.csv
Copied: Q69706.csv -> 58509c07-6415-45e5-bb3a-868e5ee40f28.csv
Copied: Q69713.csv -> b6c54847-bcf2-4b7e-bf91-3e1212697661.csv
Copied: Q69716.csv -> 0ff7e099-588f-4557-b733-00688c02d748.csv
Copied: Q69717.csv -> a13a02ba-9542-46f3-9a9b-fc9d13926265.csv
Copied: Q69718.csv -> 0b216ba3-7491-412c-abe8-b07ec4dad742.csv
Copied: Q69719.csv -> 5164e14e-01b6-4c86-a488-91963ec06baa.csv
Copied: Q69720.csv -> f35abe24-e8d7-4712-a1c6-156bcd35953c.csv
Copied: Q69721.csv -> d592f470-e074-4ad0-99a3-fb5f8042d65c.csv
Copied: Q69722.csv -> 421a35d8-f62a-4b8e-8157-9b2492e45340.csv
Copied: Q69723.csv -> ed0a87fe-fa8d-4495-a67b-32ba331cc62c.csv
Copied: Q69724.csv -> 2a33f81c-c6d1-4424-a840-45ffa7ba54d6.csv
Copied: Q69725.csv -> dbef26b0-7931-455b-b846-6485d93b34b1.csv
Copied: Q69727.csv -> 61b7365a-4977-47c6-9500-2fb1cb543dc4.csv
Copied: Q69730.csv -> 9fe64cce-13b4-4584-bdb0-400ca8acaa48.csv
Copied: Q69752.csv -> 2676d24e-2732-4740-a822-5ab7de0b3bed.csv
Copied: Q69753.csv -> 90841a44-59e9-41f3-8daf-46fcbba8ab6b.csv
Copied: Q69755.csv -> b52649cb-9e36-47ca-b37b-802fa20e5dfc.csv
Copied: Q69756.csv -> 7aaad55b-d8d6-4f6f-b185-840b8c3ec2d6.csv
Copied: Q69759.csv -> 9a33f97b-89f5-449a-9114-9e94070f8efe.csv
Copied: Q69761.csv -> 031dfdd8-d3a9-4718-bcc0-32b946a705ac.csv
Copied: Q69763.csv -> ea69613b-597c-4083-9a37-c015c76e1c59.csv
Copied: Q69767.csv -> bf45842e-73a7-494f-8163-835a720c037b.csv
Copied: Q69768.csv -> 1923edbf-09e0-4e40-84c0-661a3bab1e97.csv
Copied: Q69770.csv -> 2a0f18df-cc5b-4d73-b132-9764fb6600ef.csv
Copied: Q69771.csv -> d9464022-dc8d-4575-98c4-fefa67f12349.csv
Copied: Q69774.csv -> 99583742-a6b6-487b-9e3c-4fa316c5a25a.csv
Copied: Q69775.csv -> f8ef053d-ce9e-4399-a79e-a93bc92457d0.csv
Copied: Q69776.csv -> a7101a49-dbcd-49a0-b05e-60f0ec6c129d.csv
Copied: Q69777.csv -> af5d35dc-14eb-4505-baeb-f77c8aa2efa1.csv
Copied: Q69778.csv -> 48c9ae6b-ce0a-4437-b98a-dbf7848ed907.csv
Copied: Q69781.csv -> 5fe4200b-45db-430c-9d46-c45b65563149.csv
Copied: Q69788.csv -> 81627c9a-10f6-4b84-87e5-7d3aea042699.csv
Copied: Q69790.csv -> 2a3e88c4-e702-4160-a164-21683e692268.csv
Copied: Q69794.csv -> 23b0ac25-d698-404b-a947-f8675bcdea08.csv
Copied: Q69800.csv -> 9b5ae66e-5406-4d24-88bd-d07d204f6dc2.csv
Copied: Q69802.csv -> 1aa5e9ab-bdb5-486e-b34b-e1aca7ebf48b.csv
Copied: Q69840.csv -> d1cacf3f-800a-49ee-bc4e-8df84aadaad5.csv
Copied: Q69915.csv -> b11dabc2-97e5-4c54-b961-771c3e7d9f8c.csv
Copied: Q69917.csv -> 1d7b8948-153e-4377-bc78-c16fd784e7ad.csv
Copied: Q69956.csv -> a6dd193d-06b5-4df3-9205-108171eada78.csv
Copied: Q70010.csv -> 009c37f0-618a-4d58-b81a-511a36fa0fac.csv
Copied: Q70015.csv -> b8c8130e-6426-4500-87b2-0059ea8fc7f2.csv
Copied: Q70040.csv -> c2ec140e-ec75-4ead-9777-544c502a02f9.csv
Copied: Q77199.csv -> 79770f30-cbc9-4bfa-8a6b-0dec987d1ad8.csv
Copied: Q77215.csv -> 60c22da0-28b5-4176-8734-c966db03cafc.csv