# 1. Environment

In [1]:
import json
import os
from pathlib import Path

import pandas as pd

In [2]:
BASE_DIR = Path(r"C:\\Users\\yatsyk\\Documents\\NextCloud_Synchro\\passim_BoH")
os.chdir(BASE_DIR)
BASE_DIR

FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\yatsyk\\Documents\\NextCloud_Synchro\\passim_BoH'

# 2. Paths

In [5]:
reference_csv_path = Path("01.data/01.text_editions/texts_from_Heurist/ref_all_texts.csv")
csv_folder_path = Path("04.CoMMa/00.data/03.csvs_arkindex/EXACT_MATCH")

source_texts_dir = Path("02.passim/00.passim_input/source_texts")
manuscript_jsonl_dir = Path("02.passim/00.passim_input/comma_arkindex_mss/by_page")
all_texts_output_dir = Path("02.passim/00.passim_input/comma_arkindex_mss/all_texts")
long_texts_output_dir = Path("02.passim/00.passim_input/comma_arkindex_mss/texts_over_200_chars")

source_texts_dir.mkdir(parents=True, exist_ok=True)
manuscript_jsonl_dir.mkdir(parents=True, exist_ok=True)
all_texts_output_dir.mkdir(parents=True, exist_ok=True)
long_texts_output_dir.mkdir(parents=True, exist_ok=True)

reference_csv_path, csv_folder_path

(WindowsPath('01.data/01.text_editions/texts_from_Heurist/ref_all_texts.csv'),
 WindowsPath('04.CoMMa/00.data/03.csvs_arkindex/EXACT_MATCH'))

# 3. Helper functions

## 3.1. Build reference JSONL files

In [6]:
def build_reference_jsonl(reference_csv, all_output_path, min_chars=200):
    df = pd.read_csv(reference_csv)
    df = df.dropna(subset=["Text"])
    df["Text"] = df["Text"].astype(str).str.strip()
    df = df[df["Text"] != ""]

    all_records = df.apply(
        lambda row: {
            "id": row["Work H-ID"],
            "series": "source",
            "text": row["Text"],
        },
        axis=1,
    ).tolist()

    long_df = df[df["Text"].str.len() > min_chars].copy()
    long_records = long_df.apply(
        lambda row: {
            "id": row["Work H-ID"],
            "series": "source",
            "text": row["Text"],
        },
        axis=1,
    ).tolist()

    with open(all_output_path, "w", encoding="utf-8") as handle:
        for record in all_records:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")


    print(f"Saved {len(all_records)} reference texts to {all_output_path}")

    return df, long_df

## 3.2. Convert Arkindex CSV files into manuscript JSONL files

In [7]:
def csv_to_manuscript_jsonl(csv_path, output_path):
    df = pd.read_csv(csv_path)

    required_columns = {"page_ordering", "text"}
    missing_columns = required_columns - set(df.columns)
    if missing_columns:
        raise ValueError(f"Missing required columns in {csv_path.name}: {sorted(missing_columns)}")

    df = df.sort_values("page_ordering").copy()
    df["text"] = df["text"].fillna("").astype(str).str.strip()
    df = df[df["text"] != ""]

    manuscript_id = csv_path.stem
    records = [
        {
            "id": int(row.page_ordering),
            "series": manuscript_id,
            "text": row.text,
        }
        for row in df.itertuples(index=False)
    ]

    with open(output_path, "w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")

    return len(records)


def convert_csv_folder_to_jsonl(input_folder, output_folder):
    output_folder.mkdir(parents=True, exist_ok=True)
    summary = []

    for csv_path in sorted(input_folder.glob("*.csv")):
        output_path = output_folder / f"{csv_path.stem}_HTR.jsonl"
        row_count = csv_to_manuscript_jsonl(csv_path, output_path)
        summary.append(
            {
                "manuscript_id": csv_path.stem,
                "jsonl_path": str(output_path),
                "non_empty_pages": row_count,
            }
        )

    summary_df = pd.DataFrame(summary)
    print(f"Converted {len(summary_df)} CSV files into manuscript JSONL files")
    return summary_df

## 3.3. Combine reference texts and manuscript transcription into `in.json`

In [8]:
def load_and_combine_json(ref_file, ms_file):
    combined_data = []
    for filename in [ref_file, ms_file]:
        with open(filename, "r", encoding="utf-8") as file:
            data = [json.loads(line) for line in file]
            combined_data.extend(data)
    return combined_data


def create_folders_with_combined_json(ref_path, folder_path, output_folder):
    output_folder.mkdir(parents=True, exist_ok=True)
    ms_files = sorted(folder_path.glob("*.jsonl"))

    if not ms_files:
        print(f"No .jsonl files found in {folder_path}")
        return

    for ms_file_path in ms_files:
        docs = load_and_combine_json(ref_path, ms_file_path)
        base_name = ms_file_path.stem.replace("_HTR", "") + "_in_for_passim"
        output_subfolder = output_folder / base_name
        output_subfolder.mkdir(parents=True, exist_ok=True)

        in_json_path = output_subfolder / "in.json"
        with open(in_json_path, "w", encoding="utf-8") as handle:
            for doc in docs:
                handle.write(json.dumps(doc, ensure_ascii=False) + "\n")

        print(f"Created {in_json_path}")

# 4. Export reference texts for passim

In [9]:
ref_all_jsonl_path = source_texts_dir / "ref_all_texts.jsonl"

all_texts_df, long_texts_df = build_reference_jsonl(
    reference_csv=reference_csv_path,
    all_output_path=ref_all_jsonl_path,
)

all_texts_df

Saved 14814 reference texts to 02.passim\00.passim_input\source_texts\ref_all_texts.jsonl

,Work H-ID,rec_Title,Type,textLang,Title,Text,Liturgical function,Note,Textual source,Witness (note),Id Horae,ID Arkindex,text_length
88,395034,A cunctis malis iminentibus erripiat nos omnip...,Level 4,NaN,NaN,A cunctis malis iminentibus erripiat nos omnip...,Benediction,NaN,NaN,NaN,1.0,0,70.0
89,395035,Ab hoste maligno eripiat nos Dei genitrix virg...,Level 4,NaN,NaN,Ab hoste maligno eripiat nos Dei genitrix virgo,Benediction,NaN,NaN,NaN,10.0,2f32f250-b269-4eed-a8f9-019da83619cb,47.0
90,395036,Ave magnifica misericordiae | Cantus ID 200457...,Level 4,NaN,NaN,Ave magnifica misericordiae,Antiphon,NaN,NaN,NaN,100.0,0,27.0
91,395037,Que cum audisset turbata est in sermone | HORA...,Level 4,NaN,NaN,Que cum audisset turbata est in sermone,Lesson,NaN,Lk 1:29-33,NaN,1000.0,3ef3cccd-6464-42c6-94c9-720e227f5519,39.0
92,395038,Quem credimus ex virgine natum | HORAE | | Hym...,Level 4,NaN,NaN,Quem credimus ex virgine natum,Hymn,NaN,NaN,NaN,1001.0,0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15129,725238,Precibus et meritis beatissime semper virginis...,Level 4,NaN,NaN,Precibus et meritis beatissime semper virginis...,Absolution,NaN,NaN,NaN,14811.0,e450e12c-fc24-43d9-9b27-1e6e5b480bdd,109.0
15130,725239,Precibus et meritis beatissime semperque virgi...,Level 4,NaN,NaN,Precibus et meritis beatissime semperque virgi...,Absolution,NaN,NaN,NaN,14812.0,0b750036-2e5c-43e9-ae5a-142e5e9ef8ee,112.0
15131,725240,Precibus et meritis beatissime semperque virgi...,Level 4,NaN,NaN,Precibus et meritis beatissime semperque virgi...,Absolution,NaN,NaN,NaN,14813.0,8929cc0b-966a-4563-b764-df2d30f9ecfa,117.0
15132,725241,Per virginem Mariam concedat nobis Dominus sal...,Level 4,NaN,NaN,Per virginem Mariam concedat nobis Dominus sal...,Benediction,NaN,NaN,NaN,14814.0,87c212ac-ed76-4bce-9eca-b16f66af0b09,59.0
15133,796098,Christe qui lux es et dies | Cantus ID 830070 ...,Level 4,"Latin (LA, LAT)",NaN,Christe qui lux es et dies noctis tenebras det...,Hymn,NaN,NaN,NaN,NaN,NaN,657.0

# 5. Convert CoMMa Arkindex CSV files into manuscript JSONL files

In [10]:
conversion_summary = convert_csv_folder_to_jsonl(
    input_folder=csv_folder_path,
    output_folder=manuscript_jsonl_dir,
)

conversion_summary

Converted 178 CSV files into manuscript JSONL files

,manuscript_id,jsonl_path,non_empty_pages
0,003d5be0-3453-46e9-b904-4f6d4f1ee4b5,02.passim\00.passim_input\comma_arkindex_mss\b...,125
1,0068e751-c249-4d8b-82f6-07933fe0cecd,02.passim\00.passim_input\comma_arkindex_mss\b...,135
2,009c37f0-618a-4d58-b81a-511a36fa0fac,02.passim\00.passim_input\comma_arkindex_mss\b...,288
3,02181622-2bcc-4b35-b124-63c701e25860,02.passim\00.passim_input\comma_arkindex_mss\b...,234
4,0253a5a1-0667-4c1c-b499-a59d48abc884,02.passim\00.passim_input\comma_arkindex_mss\b...,280
...,...,...,...
173,f411cb6b-7e69-4e08-bdc8-282b62469daa,02.passim\00.passim_input\comma_arkindex_mss\b...,449
174,f8ac87c1-b602-4093-8bde-419bf7a38c3d,02.passim\00.passim_input\comma_arkindex_mss\b...,267
175,f8ef053d-ce9e-4399-a79e-a93bc92457d0,02.passim\00.passim_input\comma_arkindex_mss\b...,215
176,f9f1fca3-072f-4056-9144-8aae1d4a6504,02.passim\00.passim_input\comma_arkindex_mss\b...,205
177,ff5abf5d-527f-4db5-9ae0-51222fe71a78,02.passim\00.passim_input\comma_arkindex_mss\b...,259

# 6. Create `in.json` files for passim

## 6.1. With all reference texts

In [11]:
create_folders_with_combined_json(
    ref_path=ref_all_jsonl_path,
    folder_path=manuscript_jsonl_dir,
    output_folder=all_texts_output_dir,
)

Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\003d5be0-3453-46e9-b904-4f6d4f1ee4b5_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\0068e751-c249-4d8b-82f6-07933fe0cecd_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\009c37f0-618a-4d58-b81a-511a36fa0fac_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\02181622-2bcc-4b35-b124-63c701e25860_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\0253a5a1-0667-4c1c-b499-a59d48abc884_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\031dfdd8-d3a9-4718-bcc0-32b946a705ac_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\034c35ae-17e3-4e51-9821-8cf1662b1253_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\05906f2e-0c51-472d-a1f6-b8d59502057b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\094b5d7a-c512-4290-924c-81b48dea2fd9_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\09878703-855a-425e-a0fd-239b83a81de5_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\098b9a4a-5037-4b57-a010-738c96be1506_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\0b216ba3-7491-412c-abe8-b07ec4dad742_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\0be07365-bef9-4533-81cc-3f6248f58663_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\0d54dc8b-b5fd-4ced-9191-b59cc5eb198e_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\0ff7e099-588f-4557-b733-00688c02d748_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\16924cb7-fac5-4683-8f11-89cf7f0e5ffe_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\17a645dc-d1e0-4bbb-8c48-f48ecf5bf4b9_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\1923edbf-09e0-4e40-84c0-661a3bab1e97_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\1aa5e9ab-bdb5-486e-b34b-e1aca7ebf48b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\1d7b8948-153e-4377-bc78-c16fd784e7ad_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\22005662-66f9-4803-aa23-80951b7bfadf_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\238af2e2-16a7-4fa5-93e8-b9c79620272c_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\23b0ac25-d698-404b-a947-f8675bcdea08_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\24ecc34f-2309-48d4-aa59-5f2fb77a6979_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\2676d24e-2732-4740-a822-5ab7de0b3bed_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\26c036eb-c249-4720-9229-aa622ad736c2_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\27a9ff14-517c-45cb-a233-c52d62038399_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\2a33f81c-c6d1-4424-a840-45ffa7ba54d6_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\2a3e88c4-e702-4160-a164-21683e692268_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\2a6dd8ae-86d9-427a-ba48-60ec2bbdd7e0_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\2c2d0d08-927a-40c8-97db-52223c464e89_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\2de4f389-79a1-4047-bf70-f96adb4262bb_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\2e5fd8a1-1f44-456b-b3e3-8fc147ba70dc_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\330f14b9-f6ee-40ba-a414-6bb9e86f6c7b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\339d3426-ff0c-470f-8467-4bf9677a10f5_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\33d7fd0c-7603-4f24-bd9b-b01d21b8ed54_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\385d36f7-d042-4c43-a260-a480e059ccdd_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\3a230fb6-4f75-480c-9cd4-c70ac2bfc432_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\3f5df301-10e6-4833-8110-76d20188ffd5_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\3ff1cb7d-43ba-41aa-90a9-1dfae271513a_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\400f000c-4f8c-405e-8531-11d3af24fad7_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\421a35d8-f62a-4b8e-8157-9b2492e45340_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\47ad0f42-5f58-4a6c-ac01-8fbb98e0b8af_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\4d70e010-afa1-40fc-8ab3-9b59e2eb7371_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\4f057d86-0d95-4b6f-ac96-aa7968d8c855_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\5164e14e-01b6-4c86-a488-91963ec06baa_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\5365917a-1655-4902-b6bc-e282c0a5f996_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\544dc6c3-d5f6-4bff-a89e-57dfa4e8accb_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\54fc41f3-a39f-4375-b7d0-26abc9c71aed_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\5767de2b-8dea-47d6-b18e-6744c0e5805a_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\58422672-e5af-402b-b81b-7d928e230c36_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\58509c07-6415-45e5-bb3a-868e5ee40f28_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\5d8fd1ad-2d65-4aa8-8938-f4d757b2c840_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\5fe2eace-2177-4fa0-8c84-2b94b3d88c00_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\5fe4200b-45db-430c-9d46-c45b65563149_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\60c22da0-28b5-4176-8734-c966db03cafc_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\61334867-7364-4b1e-bfdf-01d12f8aee0f_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\6150a30a-bff0-4672-96c6-9c19896cdc5e_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\61b7365a-4977-47c6-9500-2fb1cb543dc4_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\69ff71ed-f7d0-47f2-9fe6-b8d218a965aa_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\6a06c371-4b5d-4f33-b1d9-398b6c2b90c4_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\6b67c8df-ef4d-40a5-b1b5-ada35871f281_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\6d0f8a3f-ce06-4d48-ace2-46043ac02b6d_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\6d6e6acd-393b-4f66-bdd5-4d9f06ad5c24_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\6ddaaadd-ffcc-4433-b7f3-0b4b802a984b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\6fbc9fe5-976a-4778-aac0-38b82f634fe4_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\70a2eedd-8653-40ef-8284-ad2612e37635_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\70aadb9e-fc7f-4583-afef-de71ecca65c6_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\71d753bc-6f88-4d39-b301-71f78ba8d39b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\739f2469-8006-4ed5-acdb-29e748c6af92_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\73e26638-6275-41b9-9502-39e27f01d93f_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\75ad7682-7b48-4226-90dd-751d8a4fd938_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\774f1529-1628-435d-9a1e-39fefb4ba648_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\77fcbfe1-faf8-4316-8f32-0155ed3a60c5_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\79770f30-cbc9-4bfa-8a6b-0dec987d1ad8_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\7aaad55b-d8d6-4f6f-b185-840b8c3ec2d6_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\7c9ed905-8499-452f-86d5-d354b5f1071c_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\81627c9a-10f6-4b84-87e5-7d3aea042699_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\82c6c1e4-ac24-4b3b-ab78-c795c2f3fd66_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\837e8a45-af01-487b-98d2-f1705b38d867_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\85f2e2d9-4558-4906-93f4-98b64a558c69_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\87b6ac6d-df52-4e78-a8c9-560b615d37f3_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\886383bb-9a55-4606-90ce-6cc6e5a8f10a_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\8b860405-c988-4e4c-975a-5246a6c0dae8_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\8c28a6eb-1978-4368-92bf-74af5fad950f_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\8dd96669-48ec-4556-82f6-1df1e48c46f2_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\8ec3994a-ab25-497e-bb0e-ede0c47d763a_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\90841a44-59e9-41f3-8daf-46fcbba8ab6b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\94f75d6a-76ac-486d-a78b-3d3cdef63ae5_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\98e034ec-9c99-4d46-b7d4-95677c120369_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\98efcd16-6ab5-4532-9b40-9c88010738f3_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\99583742-a6b6-487b-9e3c-4fa316c5a25a_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9a33f97b-89f5-449a-9114-9e94070f8efe_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9a607547-15d2-4dac-a3e2-326d74b4322f_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9acdbfe6-cd66-4671-b83a-12957f42e122_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9b368755-771a-4457-9ee8-332e548b3e57_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9b5ae66e-5406-4d24-88bd-d07d204f6dc2_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9bcf2874-1130-479f-8b6a-8c5f555e9ca3_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9faef44b-a346-4f81-92ca-aadf5c9d50b1_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9fb79d58-9c62-49eb-896f-a61ddcccd9e7_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\9fe64cce-13b4-4584-bdb0-400ca8acaa48_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\a0892db5-9dd9-466a-8983-2c8d96281cc4_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\a0a16d18-2ebb-47f0-bd4f-17fc08f0b14f_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\a0c5e61b-6e08-444a-a414-1713529ae298_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\a13a02ba-9542-46f3-9a9b-fc9d13926265_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\a6dd193d-06b5-4df3-9205-108171eada78_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\a7101a49-dbcd-49a0-b05e-60f0ec6c129d_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\a7bb2ecc-e89c-4805-8378-8dc8163cb582_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\a9a01b20-b6cc-43e1-b3cd-4b57bb3fc270_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\aa28246a-8c88-42df-843a-53340feb702a_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\aa3ec7e1-edcd-47b1-ae86-86ee618b0143_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\ac898936-263d-46bb-8e0a-a3d720b03f2c_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\adbef7db-ff17-4e2e-95b2-4425a5bd5838_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\af5d35dc-14eb-4505-baeb-f77c8aa2efa1_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\afcc0a79-fe57-41b0-b801-a5340a282ddb_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b11dabc2-97e5-4c54-b961-771c3e7d9f8c_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b381f783-cf7e-41b9-baa0-762d68688194_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b3b9759b-56e1-460d-b766-8cee25d6aaa5_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b4fcd76d-9907-47ef-8672-acf6f026bb37_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b52649cb-9e36-47ca-b37b-802fa20e5dfc_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b6c54847-bcf2-4b7e-bf91-3e1212697661_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b7cce76f-9297-4fef-b361-1d88c1a7a255_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b812c2af-f58d-49bc-89bb-982cb72e9ee1_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\b8c8130e-6426-4500-87b2-0059ea8fc7f2_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\bab3de6f-980c-4b6c-99ab-b438140e949f_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\bb6587f3-ad2a-48f3-94ca-758e3650e35b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\bb9f8afc-77b1-4fde-9a45-8152e4ec090c_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\bd38bf32-d4dc-4e08-a677-7a955c3fa3eb_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\bec31bce-ab48-4a1a-927a-cc83d7237f95_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\bf45842e-73a7-494f-8163-835a720c037b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c0b8fea9-df2b-4518-a55e-5337fa54ce13_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c12d6a75-6223-41ad-8a82-0f634a5f2e13_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c185edee-94f8-412f-b3e3-2c5bb5fe2593_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c2ec140e-ec75-4ead-9777-544c502a02f9_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c2fbe77e-b779-48ac-82ad-46a29b5d6562_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c3f3f006-642b-419d-8b15-8e6dbab11a72_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c855a644-405f-4262-bc24-73565c447135_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c8b5b12d-bd57-4a52-a88c-66cc2601f589_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\c91bd11b-ee02-4a1e-8c1b-b82310666875_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\cb0bb7a4-14b6-4a49-af00-e1d8cd9bc3c7_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\cb8cf8d1-59e8-4bfd-9c34-6f35193a4f63_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\cbb23979-72fc-48a3-bf59-0963fc91c1ed_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\cc24f856-d46e-4c7c-908b-5565821f0198_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\ce56cfe8-390c-4227-95d2-211bb48b4e4b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\cf1ecf87-1825-4923-948d-0adf1cceaac0_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\cf3b0414-e535-4f20-8dc8-52316b4f7d4a_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\d1cda616-216c-4cc2-b796-f3b00deaac67_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\d2d18aab-f327-424c-b391-361434dde1d0_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\d592f470-e074-4ad0-99a3-fb5f8042d65c_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\d8d587d4-0394-47a2-b540-c564f8ecbd22_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\d9464022-dc8d-4575-98c4-fefa67f12349_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\d9dd2c1b-6994-4eaa-ade6-fbc0df311a4e_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\dbef26b0-7931-455b-b846-6485d93b34b1_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\dc364c97-758e-4622-8492-1623b49b69a5_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\de49ef85-cbf5-48b1-a70d-a44a77f6f9ca_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\e3b1fc5f-8410-4ef8-94d4-9421fbefed22_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\e43c93f2-5f70-475a-8475-8d8131260b3d_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\e696ac54-e46e-4b0a-88b4-7f8e1f08f7ae_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\e741feb8-6ac4-48f9-8dca-af231bb7b862_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\e91794e0-6320-49d5-bd99-f4b42394eb6b_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\e9cc30a1-1528-411c-970c-57b0e417d964_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\ea69613b-597c-4083-9a37-c015c76e1c59_in_for_passim\in.json
Created 02.passim\00.passim_input\comma_arkindex_mss\all_texts\eacdb93a-1018-4f5a-8d02-3313f6d27a25_in_for_passim\in.json